
-- +migrate Up
ALTER TYPE notification_type
ADD VALUE IF NOT EXISTS 'TICKET_REASSIGNED';

ALTER TYPE notification_type
ADD VALUE IF NOT EXISTS 'TICKET_ENGINEER_RESOLUTION';

-- +migrate Down
ALTER TYPE notification_type
DROP VALUE IF EXISTS 'TICKET_REASSIGNED';

ALTER TYPE notification_type
DROP VALUE IF EXISTS 'TICKET_ENGINEER_RESOLUTION';